# Simple LSTM

## 1) data 는 0 ~ 99 까지의 연속된 숫자이고, target 은 (1 ~ 101) * 2 으로 구성한다. 입력  data 에 대응하는 출력 data 를 예측하는 model 을 LSTM 으로 작성

## 연속된 5 개의 숫자를 보고 다음 숫자를 알아맞추도록 LSTM 을 이용한 model 작성

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

### Training Data 작성 요령

In [2]:
numbers = [[i] for i in range(105)]
numbers[:5]

[[0], [1], [2], [3], [4]]

In [3]:
data = []
target = []
for i in range(5, len(numbers)):
    data.append(numbers[i-5: i])
    target.append(numbers[i][0] * 2)

print(data[5])
print(target[5])

[[5], [6], [7], [8], [9]]
20


In [4]:
# List --> numpy ndarray 변환
data = np.array(data, dtype="float32")
target = np.array(target, dtype="float32")

# Normalize
data = data / 100.
target = target / 100.

In [5]:
data.shape, target.shape

((100, 5, 1), (100,))

In [6]:
model = Sequential()
model.add(LSTM(16, input_shape=(5, 1)))
model.add(Dense(1))

In [7]:
model.compile(optimizer='adam', loss='mae', metrics=['mae'])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 16)                1152      
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
Total params: 1,169
Trainable params: 1,169
Non-trainable params: 0
_________________________________________________________________


In [9]:
history = model.fit(data, target, epochs=300, validation_split=0.2)

Epoch 1/300
3/3 [==============================] - 2s 237ms/step - loss: 0.8307 - mae: 0.8307 - val_loss: 1.7347 - val_mae: 1.7347
Epoch 2/300
3/3 [==============================] - 0s 11ms/step - loss: 0.8042 - mae: 0.8042 - val_loss: 1.6935 - val_mae: 1.6935
Epoch 3/300
3/3 [==============================] - 0s 11ms/step - loss: 0.7772 - mae: 0.7772 - val_loss: 1.6517 - val_mae: 1.6517
Epoch 4/300
3/3 [==============================] - 0s 9ms/step - loss: 0.7502 - mae: 0.7502 - val_loss: 1.6090 - val_mae: 1.6090
Epoch 5/300
3/3 [==============================] - 0s 10ms/step - loss: 0.7230 - mae: 0.7230 - val_loss: 1.5649 - val_mae: 1.5649
Epoch 6/300
3/3 [==============================] - 0s 10ms/step - loss: 0.6937 - mae: 0.6937 - val_loss: 1.5192 - val_mae: 1.5192
Epoch 7/300
3/3 [==============================] - 0s 10ms/step - loss: 0.6646 - mae: 0.6646 - val_loss: 1.4709 - val_mae: 1.4709
Epoch 8/300
3/3 [==============================] - 0s 10ms/step - loss: 0.6335 - mae: 0.63

Epoch 64/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0142 - mae: 0.0142 - val_loss: 0.0101 - val_mae: 0.0101
Epoch 65/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0136 - mae: 0.0136 - val_loss: 0.0156 - val_mae: 0.0156
Epoch 66/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0131 - mae: 0.0131 - val_loss: 0.0149 - val_mae: 0.0149
Epoch 67/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0126 - mae: 0.0126 - val_loss: 0.0226 - val_mae: 0.0226
Epoch 68/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0127 - mae: 0.0127 - val_loss: 0.0126 - val_mae: 0.0126
Epoch 69/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0127 - mae: 0.0127 - val_loss: 0.0231 - val_mae: 0.0231
Epoch 70/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0137 - mae: 0.0137 - val_loss: 0.0111 - val_mae: 0.0111
Epoch 71/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0123 - mae: 

3/3 [==============================] - 0s 9ms/step - loss: 0.0065 - mae: 0.0065 - val_loss: 0.0470 - val_mae: 0.0470
Epoch 127/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0067 - mae: 0.0067 - val_loss: 0.0590 - val_mae: 0.0590
Epoch 128/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0071 - mae: 0.0071 - val_loss: 0.0553 - val_mae: 0.0553
Epoch 129/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0064 - mae: 0.0064 - val_loss: 0.0524 - val_mae: 0.0524
Epoch 130/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0068 - mae: 0.0068 - val_loss: 0.0605 - val_mae: 0.0605
Epoch 131/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0066 - mae: 0.0066 - val_loss: 0.0537 - val_mae: 0.0537
Epoch 132/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0065 - mae: 0.0065 - val_loss: 0.0547 - val_mae: 0.0547
Epoch 133/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0066 - mae: 0.0066

3/3 [==============================] - 0s 11ms/step - loss: 0.0059 - mae: 0.0059 - val_loss: 0.0603 - val_mae: 0.0603
Epoch 189/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0062 - mae: 0.0062 - val_loss: 0.0521 - val_mae: 0.0521
Epoch 190/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0555 - val_mae: 0.0555
Epoch 191/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0556 - val_mae: 0.0556
Epoch 192/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0535 - val_mae: 0.0535
Epoch 193/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0590 - val_mae: 0.0590
Epoch 194/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0061 - mae: 0.0061 - val_loss: 0.0554 - val_mae: 0.0554
Epoch 195/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0062 - mae: 0.0062 

3/3 [==============================] - 0s 9ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0507 - val_mae: 0.0507
Epoch 251/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0065 - mae: 0.0065 - val_loss: 0.0417 - val_mae: 0.0417
Epoch 252/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0063 - mae: 0.0063 - val_loss: 0.0622 - val_mae: 0.0622
Epoch 253/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0409 - val_mae: 0.0409
Epoch 254/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0072 - mae: 0.0072 - val_loss: 0.0548 - val_mae: 0.0548
Epoch 255/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0079 - mae: 0.0079 - val_loss: 0.0552 - val_mae: 0.0552
Epoch 256/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0060 - mae: 0.0060 - val_loss: 0.0491 - val_mae: 0.0491
Epoch 257/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0061 - mae: 0.0061 -

In [10]:
test_data = [[35], [36], [37], [38], [39]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 320ms/step


array([[79.395226]], dtype=float32)

In [11]:
test_data = [[5], [6], [7], [8], [9]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 11ms/step


array([[20.733553]], dtype=float32)

In [12]:
test_data = [[60], [61], [62], [63], [64]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 12ms/step


array([[130.0133]], dtype=float32)