# Simple LSTM

## 1) data 는 0 ~ 99 까지의 연속된 숫자이고, target 은 (1 ~ 101) * 2 으로 구성한다. 입력  data 에 대응하는 출력 data 를 예측하는 model 을 LSTM 으로 작성

## 연속된 5 개의 숫자를 보고 다음 숫자를 알아맞추도록 LSTM 을 이용한 model 작성

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM

### Training Data 작성 요령

In [2]:
numbers = [[i] for i in range(105)]
numbers[:5]

[[0], [1], [2], [3], [4]]

In [3]:
data = []
target = []
for i in range(5, len(numbers)):
    data.append(numbers[i-5: i])
    target.append(numbers[i][0] * 2)

print(data[5])
print(target[5])

[[5], [6], [7], [8], [9]]
20


In [4]:
# List --> numpy ndarray 변환
data = np.array(data, dtype="float32")
target = np.array(target, dtype="float32")

# Normalize
data = data / 100.
target = target / 100.

In [5]:
data.shape, target.shape

((100, 5, 1), (100,))

In [6]:
model = Sequential()
model.add(LSTM(16, input_shape=(5, 1)))
model.add(Dense(1))

In [7]:
model.compile(optimizer='adam', loss='mae', metrics=['mae'])

In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 16)                1152      
                                                                 
 dense (Dense)               (None, 1)                 17        
                                                                 
Total params: 1,169
Trainable params: 1,169
Non-trainable params: 0
_________________________________________________________________


In [9]:
history = model.fit(data, target, epochs=300, validation_split=0.2)

Epoch 1/300
3/3 [==============================] - 2s 245ms/step - loss: 0.8792 - mae: 0.8792 - val_loss: 1.8428 - val_mae: 1.8428
Epoch 2/300
3/3 [==============================] - 0s 10ms/step - loss: 0.8550 - mae: 0.8550 - val_loss: 1.8043 - val_mae: 1.8043
Epoch 3/300
3/3 [==============================] - 0s 12ms/step - loss: 0.8302 - mae: 0.8302 - val_loss: 1.7650 - val_mae: 1.7650
Epoch 4/300
3/3 [==============================] - 0s 10ms/step - loss: 0.8046 - mae: 0.8046 - val_loss: 1.7244 - val_mae: 1.7244
Epoch 5/300
3/3 [==============================] - 0s 10ms/step - loss: 0.7782 - mae: 0.7782 - val_loss: 1.6822 - val_mae: 1.6822
Epoch 6/300
3/3 [==============================] - 0s 11ms/step - loss: 0.7505 - mae: 0.7505 - val_loss: 1.6380 - val_mae: 1.6380
Epoch 7/300
3/3 [==============================] - 0s 11ms/step - loss: 0.7216 - mae: 0.7216 - val_loss: 1.5913 - val_mae: 1.5913
Epoch 8/300
3/3 [==============================] - 0s 11ms/step - loss: 0.6912 - mae: 0.6

Epoch 64/300
3/3 [==============================] - 0s 11ms/step - loss: 0.0172 - mae: 0.0172 - val_loss: 0.0112 - val_mae: 0.0112
Epoch 65/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0171 - mae: 0.0171 - val_loss: 0.0227 - val_mae: 0.0227
Epoch 66/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0152 - mae: 0.0152 - val_loss: 0.0131 - val_mae: 0.0131
Epoch 67/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0151 - mae: 0.0151 - val_loss: 0.0200 - val_mae: 0.0200
Epoch 68/300
3/3 [==============================] - 0s 13ms/step - loss: 0.0146 - mae: 0.0146 - val_loss: 0.0154 - val_mae: 0.0154
Epoch 69/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0150 - mae: 0.0150 - val_loss: 0.0163 - val_mae: 0.0163
Epoch 70/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0143 - mae: 0.0143 - val_loss: 0.0205 - val_mae: 0.0205
Epoch 71/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0139 - m

3/3 [==============================] - 0s 10ms/step - loss: 0.0080 - mae: 0.0080 - val_loss: 0.0579 - val_mae: 0.0579
Epoch 127/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0081 - mae: 0.0081 - val_loss: 0.0584 - val_mae: 0.0584
Epoch 128/300
3/3 [==============================] - 0s 11ms/step - loss: 0.0080 - mae: 0.0080 - val_loss: 0.0582 - val_mae: 0.0582
Epoch 129/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0083 - mae: 0.0083 - val_loss: 0.0608 - val_mae: 0.0608
Epoch 130/300
3/3 [==============================] - 0s 12ms/step - loss: 0.0083 - mae: 0.0083 - val_loss: 0.0601 - val_mae: 0.0601
Epoch 131/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0084 - mae: 0.0084 - val_loss: 0.0560 - val_mae: 0.0560
Epoch 132/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0080 - mae: 0.0080 - val_loss: 0.0653 - val_mae: 0.0653
Epoch 133/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0088 - mae: 0.

3/3 [==============================] - 0s 11ms/step - loss: 0.0092 - mae: 0.0092 - val_loss: 0.0599 - val_mae: 0.0599
Epoch 189/300
3/3 [==============================] - 0s 11ms/step - loss: 0.0087 - mae: 0.0087 - val_loss: 0.0707 - val_mae: 0.0707
Epoch 190/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0072 - mae: 0.0072 - val_loss: 0.0514 - val_mae: 0.0514
Epoch 191/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0092 - mae: 0.0092 - val_loss: 0.0654 - val_mae: 0.0654
Epoch 192/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0089 - mae: 0.0089 - val_loss: 0.0657 - val_mae: 0.0657
Epoch 193/300
3/3 [==============================] - 0s 9ms/step - loss: 0.0079 - mae: 0.0079 - val_loss: 0.0536 - val_mae: 0.0536
Epoch 194/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0076 - mae: 0.0076 - val_loss: 0.0730 - val_mae: 0.0730
Epoch 195/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0088 - mae: 0.00

3/3 [==============================] - 0s 11ms/step - loss: 0.0085 - mae: 0.0085 - val_loss: 0.0646 - val_mae: 0.0646
Epoch 251/300
3/3 [==============================] - 0s 11ms/step - loss: 0.0075 - mae: 0.0075 - val_loss: 0.0643 - val_mae: 0.0643
Epoch 252/300
3/3 [==============================] - 0s 12ms/step - loss: 0.0078 - mae: 0.0078 - val_loss: 0.0543 - val_mae: 0.0543
Epoch 253/300
3/3 [==============================] - 0s 11ms/step - loss: 0.0072 - mae: 0.0072 - val_loss: 0.0680 - val_mae: 0.0680
Epoch 254/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0072 - mae: 0.0072 - val_loss: 0.0641 - val_mae: 0.0641
Epoch 255/300
3/3 [==============================] - 0s 12ms/step - loss: 0.0069 - mae: 0.0069 - val_loss: 0.0630 - val_mae: 0.0630
Epoch 256/300
3/3 [==============================] - 0s 10ms/step - loss: 0.0069 - mae: 0.0069 - val_loss: 0.0658 - val_mae: 0.0658
Epoch 257/300
3/3 [==============================] - 0s 11ms/step - loss: 0.0066 - mae: 0.

In [10]:
test_data = [[35], [36], [37], [38], [39]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 365ms/step


array([[79.736]], dtype=float32)

In [11]:
test_data = [[5], [6], [7], [8], [9]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 13ms/step


array([[21.131681]], dtype=float32)

In [12]:
test_data = [[60], [61], [62], [63], [64]]

x = np.array(test_data, dtype="float32") / 100.

model.predict(x.reshape(1, 5, 1)) * 100

1/1 [==============================] - 0s 13ms/step


array([[130.62839]], dtype=float32)